version: "3"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqubedb
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
     # - SONAR.SEARCH.JAVAADDITIONALOPTS: -Dbootstrap.system_call_filter=false
    volumes:
      - /root/workspace/volume/sonarCE/data:/opt/sonarqube/data
      - /root/workspace/volume/sonarCE/extentions:/opt/sonarqube/extensions
      - /root/workspace/volume/sonarCE/logs/:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqubedb
    volumes:
      - /root/workspace/volume/postgresql/:/var/lib/postgresql
      - /root/workspace/volume/postgresql/data:/var/lib/postgresql/data
